apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deniskachar-com-ingress
spec:
  tls:
  - hosts:
    - deniskachar.com
    secretName: deniskachar-com-tls
  rules:
  - host: deniskachar.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deniskachar-com-service
            port:
              number: 80
