apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deniskachar-cert
spec:
  secretName: deniskachar-com-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - deniskachar.com
